<a href="https://colab.research.google.com/github/LawrenceEldrichMercado/58013-LINEAR-ALGEBRA/blob/main/Long_Quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array ([[1, 2, 3],
              [4, 5, 6]])
B = np.array ([[1,2],
               [3, 4],
               [5, 6]])
AB = np.dot(A, B)

D = np.array ([[1, 2],
               [3, 4]])

DD = D + D

C = np.array ([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
two_C = 2 * C

print("AB:")
print(AB)

print ("D + D:")
print(DD)

print("2C:")
print(two_C)

AB:
[[22 28]
 [49 64]]
D + D:
[[2 4]
 [6 8]]
2C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [2]:
import numpy as np

A = np.array ([2, 7, 4])
B = np.array ([3, 9, 8])

cross_product = np.cross (A,B)

print ("Cross Product of A and B")
print(cross_product)

Cross Product of A and B
[20 -4 -3]
