<a href="https://colab.research.google.com/github/LawrenceEldrichMercado/58013-LINEAR-ALGEBRA/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [ ]:
import numpy as np
#Multiplication
# Define the range of numbers for the table (1 to 10)
numbers = np.arange(1, 11)

# Create a multiplication table using NumPy broadcasting
table = np.multiply.outer(numbers, numbers)

# Print the multiplication table
for row in table:
    print(" ".join(f"{num:2d}" for num in row))

 1  2  3  4  5  6  7  8  9 10
 2  4  6  8 10 12 14 16 18 20
 3  6  9 12 15 18 21 24 27 30
 4  8 12 16 20 24 28 32 36 40
 5 10 15 20 25 30 35 40 45 50
 6 12 18 24 30 36 42 48 54 60
 7 14 21 28 35 42 49 56 63 70
 8 16 24 32 40 48 56 64 72 80
 9 18 27 36 45 54 63 72 81 90
10 20 30 40 50 60 70 80 90 100


Question 2

In [9]:
import numpy as np

# Define the range of numbers for the table (1 to 10)
numbers = np.arange(1, 11)

# Create a multiplication table using NumPy broadcasting
table = np.multiply.outer(numbers, numbers)

# Double all the values in the table
table_doubled = table * 2

# Print the doubled multiplication table
for row in table_doubled:
    print(" ".join(f"{num:4d}" for num in row))

   2    4    6    8   10   12   14   16   18   20
   4    8   12   16   20   24   28   32   36   40
   6   12   18   24   30   36   42   48   54   60
   8   16   24   32   40   48   56   64   72   80
  10   20   30   40   50   60   70   80   90  100
  12   24   36   48   60   72   84   96  108  120
  14   28   42   56   70   84   98  112  126  140
  16   32   48   64   80   96  112  128  144  160
  18   36   54   72   90  108  126  144  162  180
  20   40   60   80  100  120  140  160  180  200


Question 3

In [5]:

import numpy as np
# Specify the size of the square matrix (e.g., 4x4)
matrix_size = 4

# Create an identity matrix using NumPy
identity_matrix = np.eye(matrix_size)

# Print the identity matrix
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 4

In [6]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Question 5

In [8]:
import numpy as np

# Define arrayOne and arrayTwo
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

# Add arrayOne and arrayTwo
result_array = arrayOne + arrayTwo

# Calculate the square of each element in the result array
result_array_squared = np.square(result_array)

print("Result Array (After Addition):")
print(result_array)

print("\nResult Array (After Squaring Each Element):")
print(result_array_squared)


Result Array (After Addition):
[[20 39 33]
 [25 25 28]]

Result Array (After Squaring Each Element):
[[ 400 1521 1089]
 [ 625  625  784]]
