<a href="https://colab.research.google.com/github/LawrenceEldrichMercado/58013-LINEAR-ALGEBRA/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

A+B+C
print(np.add(A,np.add(B,C)))
np.sum(B)


[ 4  3 -1]


2

In [2]:
np.subtract(A,B)

A-B

array([-2,  1,  2])

In [3]:
np.multiply(A,B)

A*B

array([3, 2, 0])

In [4]:
np.divide(A,B)

A/B

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
print(C/D)

np.array(A/B,dtype=int)

[3.9 1.8 7.7]


array([0, 2, 0])