<a href="https://colab.research.google.com/github/LawrenceEldrichMercado/58013-LINEAR-ALGEBRA/blob/main/Vectors%2C_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A=np.array([4,3])
B=np.array([2,-5])

print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [2]:
import numpy as np
#Size Dimension, Size
### Checking shapes
### Shapes tells us how many rows and columns are there
ball1=np.array([1,2,3])
ball2=np.array([0,1,-1])
print(ball1)
print(ball2)
#ball= np.shape([[ball1],[ball2]])
ball=np.shape(ball1)
balls=np.shape(ball2)
z= ball+balls
print(z)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [3]:
#Addition
import numpy as np
A= np.array([4,3])
B=([2,-5])
R= np.add(A,B)
print(R)

[ 6 -2]


In [5]:
#Subtraction
import numpy as np
A= np.array([4,3])
B=([2,-5])
R1= np.subtract(A,B)
print(R1)
R2= np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


In [6]:
#Scalar Product
import numpy as np
S= np.array([2])
V= S*A
print(V)

[8 6]


In [7]:
#Dot Product
import numpy as np
a= np.array([2])
b= np.array([4])
c= np.dot(a,b)
print(c)


8


In [9]:
#Property of Matrix
#Identity of Matrix

c= np.eye (3,3)
print(c)

#Zero Matrix
d= np.zeros([5,5])
print(d)
#Full Matrix
e=np.full((3,3),7)
print(e)
#Transpose Matrix
f= np.transpose(A)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
